export const SCOPES = [
  '*',
  'alert:*',
  'alert:read',
  'alert:write',
  'argo:*',
  'argo:applications:get',
  'argo:projects:get',
  'config:*',
  'config:read',
  'config:write',
  'dashboard:read',
  'deployment:*',
  'deployment:read',
  'deployment:write',
  'discovery:read',
  'fieldmap:*',
  'fieldmap:read',
  'fieldmap:write',
  'helm:*',
  'helm:compile',
  'helm:create_topics',
  'helm:execute_ddl',
  'hunt:*',
  'hunt:execute',
  'hunt:read',
  'hunt:write',
  'org:read',
  'org:write',
  'query:*',
  'query:execute',
  'query:read',
  'query:write',
  'schema:delete',
  'schema:read',
  'schema:write',
  'service:*:config:*',
  'service:*:config:read',
  'service:*:metrics:read',
  'source:*',
  'source:read',
  'source:write',
  'transforms:*',
  'transforms:compile',
  'transforms:test',
];

export const UI_DISPLAY_ACTIONS = {
  ALERT_READ: 'alert:read',
  ALERT_WRITE: 'alert:write',
  ARGO_APPLICATIONS: 'argo:applications',
  ARGO_APPLICATIONS_GET: 'argo:applications:get',
  ARGO_PROJECTS: 'argo:projects',
  ARGO_PROJECTS_GET: 'argo:projects:get',
  CONFIG_READ: 'config:read',
  CONFIG_WRITE: 'config:write',
  DASHBOARD_READ: 'dashboard:read',
  DEPLOYMENT_READ: 'deployment:read',
  DEPLOYMENT_WRITE: 'deployment:write',
  DISCOVERY_READ: 'discovery:read',
  FIELDMAP_READ: 'fieldmap:read',
  FIELDMAP_WRITE: 'fieldmap:write',
  HELM_COMPILE: 'helm:compile',
  HELM_CREATE_TOPICS: 'helm:create_topics',
  HELM_EXECUTE_DDL: 'helm:execute_ddl',
  HUNT_EXECUTE: 'hunt:execute',
  HUNT_READ: 'hunt:read',
  HUNT_WRITE: 'hunt:write',
  ORG_READ: 'org:read',
  ORG_WRITE: 'org:write',
  QUERY_EXECUTE: 'query:execute',
  QUERY_READ: 'query:read',
  QUERY_WRITE: 'query:write',
  SCHEMA_DELETE: 'schema:delete',
  SCHEMA_READ: 'schema:read',
  SCHEMA_WRITE: 'schema:write',
  SERVICE_CONFIG_READ: 'service:*:config:read',
  SERVICE_CONFIG_WRITE: 'service:*:config:write',
  SERVICE_METRICS_READ: 'service:*:metrics:read',
  SOURCE_READ: 'source:read',
  SOURCE_WRITE: 'source:write',
  TRANSFORMS_COMPILE: 'transforms:compile',
  TRANSFORMS_TEST: 'transforms:test',
};
export type UI_DISPLAY_ACTIONS_TYPE =
  (typeof UI_DISPLAY_ACTIONS)[keyof typeof UI_DISPLAY_ACTIONS];
