import type { paths } from '@repo/dfe-engine-types';

export const API_CONFIG = Object.freeze({
  auth: {
    login: '/api/v1/auth/login',
    setupStatus: '/api/v1/auth/setup-status',
    refresh: '/api/v1/auth/refresh',
    me: '/api/v1/auth/me',
    permissions: '/api/v1/auth/permissions',
  },
  sources: {
    default: '/api/v1/sources',
    source: '/api/v1/sources/{name}',
    sourceColumns: '/api/v1/sources/{name}/columns',
    sourceBuild: '/api/v1/sources/{name}/build',
    sourceVersion: '/api/v1/sources/{name}/versions/{version}',
    bulk: '/api/v1/sources/bulk',
    seed: '/api/v1/sources/seed',
    plan: '/api/v1/sources/{name}/plan',
    deploy: '/api/v1/sources/{name}/deploy',
  },
  serviceConfigs: {
    default: '/api/v1/services',
    instance: '/api/v1/services/{service}/{instance}',
    validate: '/api/v1/services/{service}/{instance}/validate',
    history: '/api/v1/services/{service}/{instance}/history',
    seed: '/api/v1/services/seed',
  },
  serviceSurfaces: {
    default: '/api/v1/service-surfaces',
    surface: '/api/v1/service-surfaces/{name}',
    refreshMetrics: '/api/v1/service-surfaces/{name}/metrics/refresh',
  },
  deployments: {
    default: '/api/v1/deployments',
    deployment: '/api/v1/deployments/{service}/{instance}',
    validate: '/api/v1/deployments/{service}/{instance}/validate',
    history: '/api/v1/deployments/{service}/{instance}/history',
    applySize: '/api/v1/deployments/{service}/{instance}/size/{size}',
    seed: '/api/v1/deployments/seed',
  },
  fieldMaps: {
    default: '/api/v1/field-maps',
    standard: '/api/v1/field-maps/{standard}',
    source: '/api/v1/field-maps/{standard}/{source}',
    seed: '/api/v1/field-maps/seed',
  },
  rules: {
    default: '/api/v1/rules',
    validate: '/api/v1/rules/validate',
    rule: '/api/v1/rules/{name}',
  },
  alerts: {
    destinations: '/api/v1/alerts/destinations',
    destination: '/api/v1/alerts/destinations/{name}',
  },
  transforms: {
    compile: '/api/v1/transforms/compile',
    test: '/api/v1/transforms/test',
  },
  schemas: {
    default: '/api/v1/schemas',
    schemaVersions: '/api/v1/schemas/definitions/{schema_path}/versions',
    schema: '/api/v1/schemas/definitions/{schema_path}',
    schemaDetail: '/api/v1/schemas/definitions/{schema_path}/versions/columns',
    elasticConvert: '/api/v1/schemas/elastic-converter',
    sampleRows: '/api/v1/schemas/{source_name}/sample-rows',
    jsonPaths: '/api/v1/schemas/{source_name}/json-paths',
    promoteField: '/api/v1/schemas/{source_name}/promote-field',
  },
  orgs: {
    default: '/api/v1/orgs',
    org: '/api/v1/orgs/{name}',
  },
  groups: {
    default: '/api/v1/auth/groups',
    group: '/api/v1/auth/groups/{name}',
    groupMembers: '/api/v1/auth/groups/{name}/members',
    groupMember: '/api/v1/auth/groups/{name}/members/{username}',
  },
  accounts: {
    default: '/api/v1/auth/accounts',
    account: '/api/v1/auth/accounts/{username}',
    resetPassword: '/api/v1/auth/accounts/{username}/reset-password',
  },
  roles: {
    default: '/api/v1/auth/roles',
    role: '/api/v1/auth/roles/{name}',
    scopes: '/api/v1/auth/roles/scopes',
  },
  hunts: {
    default: '/api/v1/hunts',
    engineStatus: '/api/v1/hunts/status',
    hunt: '/api/v1/hunts/{name}',
    huntRun: '/api/v1/hunts/{name}/run',
  },
  oidc: {
    login: '/api/v1/auth/oidc/{provider}/login',
    callback: '/api/v1/auth/oidc/{provider}/callback',
  },
  oidcProviders: {
    default: '/api/v1/auth/oidc-providers',
    provider: '/api/v1/auth/oidc-providers/{name}',
    syncGroups: '/api/v1/auth/oidc-providers/{name}/sync',
    test: '/api/v1/auth/oidc-providers/{name}/test',
    verifyLogin: '/api/v1/auth/oidc-providers/{name}/verify-login',
  },
  governance: {
    actions: '/api/v1/governance/actions',
    action: '/api/v1/governance/actions/{name}',
    policies: '/api/v1/governance/policies',
    policy: '/api/v1/governance/policies/{name}',
    invokeAction: '/api/v1/governance/actions/{name}/invoke',
    adminActions: '/api/v1/governance/admin/actions',
    adminAction: '/api/v1/governance/admin/actions/{name}',
    adminPolicies: '/api/v1/governance/admin/policies',
    adminPolicy: '/api/v1/governance/admin/policies/{name}',
    reconcileChRbac: '/api/v1/governance/ch-rbac/reconcile',
  },
  helm: {
    listFiles: '/api/v1/helm/files',
    fileVariables: '/api/v1/helm/files/{name}/vars',
    fileVariable: '/api/v1/helm/files/{name}/vars/{path}',
  },
  gitops: {
    autoMerge: '/api/v1/gitops/auto-merge',
    log: '/api/v1/gitops/log',
  },
  lifecycle: {
    default: '/api/v1/lifecycle',
    lifecycle: '/api/v1/lifecycle/{name}',
  },
  repository: {
    preferences: '/api/v1/repository/preferences',
    objects: '/api/v1/repository/objects/{scope}/{scope_id}/{namespace}',
    object: '/api/v1/repository/objects/{scope}/{scope_id}/{namespace}/{key}',
  },
  clientConfig: {
    default: '/api/v1/config/client',
  },
  system: {
    version: '/api/v1/system/version',
    settings: '/api/v1/system/settings',
    clickhouseCloud: '/api/v1/system/clickhouse-cloud',
    clickhouseCloudStart: '/api/v1/system/clickhouse-cloud/start',
    clickhouseCloudStop: '/api/v1/system/clickhouse-cloud/stop',
  },
  apiKeys: {
    default: '/api/v1/auth/api-keys',
    apiKey: '/api/v1/auth/api-keys/{short_token}',
  },
} as const satisfies Record<string, Record<string, keyof paths>>);
