/* eslint-disable no-restricted-imports */
import { UseFetchInfiniteDefaultsDriftSourcesProps } from '@/Platform/hooks/system/useFetchInifniteDefaultDriftSources/types';
import { TFetchAccountsQueryParams } from '@/Settings/hooks/accounts/useFetchInfiniteFilteredAccounts/types';

export const QUERY_KEYS = Object.freeze({
  auth: {
    login: () => ['auth', 'login'],
    setupStatus: () => ['auth', 'setup-status'],
    retireAdmin: () => ['auth', 'setup', 'retire-admin'],
    refresh: () => ['auth', 'refresh'],
    logout: () => ['auth', 'logout'],
    me: () => ['auth', 'me'],
    permissions: () => ['auth', 'permissions'],
  },
  sources: {
    default: () => ['sources'],
    source: () => ['sources', '{name}'],
    sourceFlow: () => ['sources', '{name}', 'flow'],
    sourceColumns: () => ['sources', '{name}', 'columns'],
    sourceBuild: () => ['sources', '{name}', 'build'],
    sourceVersion: () => ['sources', '{name}', 'versions', '{version}'],
    bulk: () => ['sources', 'bulk'],
    seed: () => ['sources', 'seed'],
    plan: () => ['sources', '{name}', 'plan'],
    deploy: () => ['sources', '{name}', 'deploy'],
    catalogue: () => ['sources', 'catalogue'],
    fromCatalogue: () => ['sources', 'from-catalogue', '{entry}'],
    engines: () => ['sources', 'engines'],
  },
  deployment: {
    adminLinks: () => ['deployment', 'admin-links'],
  },
  fieldMaps: {
    default: () => ['field-maps'],
    standard: () => ['field-maps', '{standard}'],
    source: () => ['field-maps', '{standard}', '{source}'],
    seed: () => ['field-maps', 'seed'],
  },
  rules: {
    default: () => ['rules'],
    validate: () => ['rules', 'validate'],
    rule: () => ['rules', '{name}'],
  },
  alerts: {
    destinations: () => ['alerts', 'destinations'],
    destination: () => ['alerts', 'destinations', '{name}'],
  },
  transforms: {
    compile: () => ['transforms', 'compile'],
    test: () => ['transforms', 'test'],
  },
  schemas: {
    default: () => ['schemas'],
    schemaVersions: () => [
      'schemas',
      'definitions',
      '{schema_path}',
      'versions',
    ],
    schemaVersionsVersion: () => [
      'schemas',
      'definitions',
      '{schema_path}',
      'versions',
      '{version}',
    ],
    schema: () => ['schemas', 'definitions', '{schema_path}'],
    schemaDetail: () => [
      'schemas',
      'definitions',
      '{schema_path}',
      'versions',
      'columns',
    ],
    elasticConvert: () => ['schemas', 'elastic-converter'],
    sampleRows: () => ['schemas', '{source_name}', 'sample-rows'],
    jsonPaths: () => ['schemas', '{source_name}', 'json-paths'],
    promoteField: () => ['schemas', '{source_name}', 'promote-field'],
  },
  orgs: {
    default: () => ['orgs'],
    org: () => ['orgs', '{name}'],
  },
  groups: {
    default: () => ['auth', 'groups'],
    group: () => ['auth', 'groups', '{name}'],
    groupMembers: () => ['auth', 'groups', '{name}', 'members'],
    groupMember: () => ['auth', 'groups', '{name}', 'members', '{username}'],
  },
  accounts: {
    default: ({
      search,
      include_core,
      blocked,
      sort_by,
      sort_order,
      page,
      per_page,
    }: TFetchAccountsQueryParams = {}) => [
      'auth',
      'accounts',
      ...(search ? ['search', search] : []),
      ...(include_core ? ['include_core', include_core] : []),
      ...(blocked ? ['blocked', blocked] : []),
      ...(sort_by ? ['sort_by', sort_by] : []),
      ...(sort_order ? ['sort_order', sort_order] : []),
      ...(page ? ['page', page] : []),
      ...(per_page ? ['per_page', per_page] : []),
    ],
    account: () => ['auth', 'accounts', '{username}'],
    rotatePassword: () => ['auth', 'accounts', '{username}', 'rotate-password'],
    resetPassword: () => ['auth', 'accounts', '{username}', 'reset-password'],
    resetCurrentUserPassword: () => ['auth', 'accounts', 'reset-password'],
    me: () => ['auth', 'accounts', 'me'],
  },
  roles: {
    default: () => ['auth', 'roles'],
    role: () => ['auth', 'roles', '{name}'],
    scopes: () => ['auth', 'roles', 'scopes'],
  },
  hunts: {
    default: () => ['hunts'],
    engineStatus: () => ['hunts', 'status'],
    hunt: () => ['hunts', '{name}'],
    huntRun: () => ['hunts', '{name}', 'run'],
  },
  oidc: {
    login: () => ['auth', 'oidc', '{provider}', 'login'],
    callback: () => ['auth', 'oidc', '{provider}', 'callback'],
  },
  oidcProviders: {
    default: () => ['auth', 'oidc-providers'],
    provider: () => ['auth', 'oidc-providers', '{name}'],
    syncGroups: () => ['auth', 'oidc-providers', '{name}', 'sync'],
    test: () => ['auth', 'oidc-providers', '{name}', 'test'],
    verifyLogin: () => ['auth', 'oidc-providers', '{name}', 'verify-login'],
  },
  governance: {
    actions: () => ['governance', 'actions'],
    action: () => ['governance', 'actions', '{name}'],
    policies: () => ['governance', 'policies'],
    policy: () => ['governance', 'policies', '{name}'],
    invokeAction: () => ['governance', 'actions', '{name}', 'invoke'],
    adminActions: () => ['governance', 'admin', 'actions'],
    adminAction: () => ['governance', 'admin', 'actions', '{name}'],
    adminPolicies: () => ['governance', 'admin', 'policies'],
    adminPolicy: () => ['governance', 'admin', 'policies', '{name}'],
    reconcileChRbac: () => ['governance', 'ch-rbac', 'reconcile'],
  },
  helm: {
    listFiles: () => ['helm', 'files'],
    fileVariables: () => ['helm', 'files', '{name}', 'vars'],
    fileVariable: () => ['helm', 'files', '{name}', 'vars', '{path}'],
  },
  apps: {
    default: () => ['apps'],
    instances: () => ['apps', '{service}', 'instances'],
    app: () => ['apps', '{service}', '{instance}'],
    config: () => ['apps', '{service}', '{instance}', 'config'],
    scaling: () => ['apps', '{service}', '{instance}', 'scaling'],
    status: () => ['apps', '{service}', '{instance}', 'status'],
    metrics: () => ['apps', '{service}', '{instance}', 'metrics'],
    metricsSeries: () => [
      'apps',
      '{service}',
      '{instance}',
      'metrics',
      'series',
    ],
    history: () => ['apps', '{service}', '{instance}', 'history'],
    routing: () => ['apps', '{service}', '{instance}', 'routing'],
    routingSync: () => ['apps', '{service}', '{instance}', 'routing', 'sync'],
    files: () => ['apps', '{service}', '{instance}', 'files', '{set_name}'],
    file: () => [
      'apps',
      '{service}',
      '{instance}',
      'files',
      '{set_name}',
      '{filename}',
    ],
    fileCopy: () => [
      'apps',
      '{service}',
      '{instance}',
      'files',
      '{set_name}',
      'copy',
    ],
    fileDryRun: () => [
      'apps',
      '{service}',
      '{instance}',
      'files',
      '{set_name}',
      'dry-run',
    ],
    fileLink: () => [
      'apps',
      '{service}',
      '{instance}',
      'files',
      '{set_name}',
      'link',
    ],
    fileLinks: () => [
      'apps',
      '{service}',
      '{instance}',
      'files',
      '{set_name}',
      'links',
    ],
    fileRelink: () => [
      'apps',
      '{service}',
      '{instance}',
      'files',
      '{set_name}',
      'relink',
    ],
  },
  backingServices: {
    default: () => ['backing-services'],
    overlayVar: () => [
      'backing-services',
      'overlays',
      '{name}',
      'vars',
      '{path}',
    ],
  },
  library: {
    default: () => ['library'],
    kinds: () => ['library', 'kinds'],
    artifact: () => ['library', '{artifact}'],
    rollback: () => ['library', '{artifact}', 'rollback'],
    state: () => ['library', '{artifact}', 'state'],
    tag: () => ['library', '{artifact}', 'tags', '{tag}'],
    usage: () => ['library', '{artifact}', 'usage'],
    versions: () => ['library', '{artifact}', 'versions'],
    version: () => ['library', '{artifact}', 'versions', '{version}'],
  },
  gitops: {
    autoMerge: () => ['gitops', 'auto-merge'],
    log: () => ['gitops', 'log'],
  },
  lifecycle: {
    default: () => ['lifecycle'],
    lifecycle: () => ['lifecycle', '{name}'],
  },
  repository: {
    preferences: () => ['repository', 'preferences'],
    objects: () => [
      'repository',
      'objects',
      '{scope}',
      '{scope_id}',
      '{namespace}',
    ],
    object: () => [
      'repository',
      'objects',
      '{scope}',
      '{scope_id}',
      '{namespace}',
      '{key}',
    ],
  },
  clientConfig: {
    default: () => ['config', 'client'],
  },
  system: {
    version: () => ['system', 'version'],
    settings: () => ['system', 'settings'],
    retention: () => ['system', 'retention'],
    clickhouseCloud: () => ['system', 'clickhouse-cloud'],
    clickhouseCloudStart: () => ['system', 'clickhouse-cloud', 'start'],
    clickhouseCloudStop: () => ['system', 'clickhouse-cloud', 'stop'],
    defaults: () => ['system', 'defaults'],
    defaultsDrift: ({
      search,
      page,
      per_page,
    }: UseFetchInfiniteDefaultsDriftSourcesProps = {}) => [
      'system',
      'defaults',
      'drift',
      ...(search ? ['search', search] : []),
      ...(page ? ['page', page] : []),
      ...(per_page ? ['per_page', per_page] : []),
    ],
    applyDefaults: () => ['system', 'defaults', 'apply'],
  },
  apiKeys: {
    default: () => ['auth', 'api-keys'],
    apiKey: () => ['auth', 'api-keys', '{short_token}'],
  },
} as const satisfies Record<
  string,
  Record<string, () => (string | number | true)[]>
>);
/* eslint-enable no-restricted-imports */
