/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/e2e/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * E2E Status
         * @description Confirm this process mounted the e2e-server helpers.
         */
        get: operations["e2e_status_api_e2e_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/e2e/seed-static": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Static
         * @description Run a named e2e seed script. Unauthenticated by design.
         *
         *     The script runs on a worker thread: it writes the deploy repo over the network,
         *     and on the event loop every other request this process serves would wait for it.
         *     It takes the same write turn as the product's own writes, so a seed never runs
         *     beside one.
         */
        post: operations["seed_static_api_e2e_seed_static_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** E2EStatusResponse */
        E2EStatusResponse: {
            /** Enabled */
            enabled: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SeedRequest */
        SeedRequest: {
            /**
             * Script
             * @enum {string}
             */
            script: "seed_setup_complete" | "seed_organisation" | "seed_dfe_admin_user" | "seed_dfe_analyst_user" | "seed_dfe_infra_user" | "seed_dfe_viewers_user" | "seed_source_with_transform" | "seed_three_transforms" | "seed_library_artefact" | "seed_app_scaling_state" | "reset_all";
        };
        /** SeedResponse */
        SeedResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    e2e_status_api_e2e_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["E2EStatusResponse"];
                };
            };
        };
    };
    seed_static_api_e2e_seed_static_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
