/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with local credentials and receive a JWT token.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh the current JWT token. Requires a valid existing token.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get the current authenticated user's info.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Permissions
         * @description Get resolved permissions for the current user's roles.
         */
        get: operations["get_permissions_api_v1_auth_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description List sources with pagination, search, and filtering.
         */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /**
         * Create Source
         * @description Create a new source from a source definition dict.
         */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source
         * @description Get a full source definition by name.
         */
        get: operations["get_source_api_v1_sources__name__get"];
        /**
         * Update Source
         * @description Update an existing source definition.
         */
        put: operations["update_source_api_v1_sources__name__put"];
        post?: never;
        /**
         * Delete Source
         * @description Delete a source by name.
         */
        delete: operations["delete_source_api_v1_sources__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Action
         * @description Perform a bulk action (enable, disable, delete) on multiple sources.
         */
        post: operations["bulk_action_api_v1_sources_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Sources
         * @description Seed built-in default source definitions. Non-destructive (skips existing).
         */
        post: operations["seed_sources_api_v1_sources_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Service Configs
         * @description List service configs with optional filtering.
         */
        get: operations["list_service_configs_api_v1_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service}/{instance}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Service Config
         * @description Get a full service config by service + instance.
         */
        get: operations["get_service_config_api_v1_services__service___instance__get"];
        /**
         * Save Service Config
         * @description Create or update a service config.
         */
        put: operations["save_service_config_api_v1_services__service___instance__put"];
        post?: never;
        /**
         * Delete Service Config
         * @description Delete a service config.
         */
        delete: operations["delete_service_config_api_v1_services__service___instance__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service}/{instance}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Service Config
         * @description Dry-run validate a service config without saving.
         */
        post: operations["validate_service_config_api_v1_services__service___instance__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service}/{instance}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Service Config History
         * @description Get git history for a service config (git-backed registries only).
         */
        get: operations["get_service_config_history_api_v1_services__service___instance__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Service Configs
         * @description Seed built-in default service configs. Non-destructive.
         */
        post: operations["seed_service_configs_api_v1_services_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Deployments
         * @description List deployment configs with optional filtering.
         */
        get: operations["list_deployments_api_v1_deployments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{service}/{instance}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deployment
         * @description Get a full deployment config by service + instance.
         */
        get: operations["get_deployment_api_v1_deployments__service___instance__get"];
        /**
         * Save Deployment
         * @description Create or update a deployment config.
         */
        put: operations["save_deployment_api_v1_deployments__service___instance__put"];
        post?: never;
        /**
         * Delete Deployment
         * @description Delete a deployment config.
         */
        delete: operations["delete_deployment_api_v1_deployments__service___instance__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{service}/{instance}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Deployment
         * @description Dry-run validate a deployment config without saving.
         */
        post: operations["validate_deployment_api_v1_deployments__service___instance__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{service}/{instance}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deployment History
         * @description Get git history for a deployment config.
         */
        get: operations["get_deployment_history_api_v1_deployments__service___instance__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/{service}/{instance}/size/{size}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Size
         * @description Apply a t-shirt size to a deployment config.
         *
         *     Updates replicas, resources, and KEDA thresholds for the given size.
         *     Returns any service config overrides that should also be applied
         *     (e.g. buffer sizes) — the caller may optionally PUT these to
         *     /api/v1/services/{service}/{instance}.
         */
        post: operations["apply_size_api_v1_deployments__service___instance__size__size__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deployments/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Deployments
         * @description Seed built-in default deployment configs. Non-destructive.
         */
        post: operations["seed_deployments_api_v1_deployments_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/field-maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Field Maps
         * @description List field maps with optional filtering.
         */
        get: operations["list_field_maps_api_v1_field_maps_get"];
        put?: never;
        /**
         * Create Field Map
         * @description Create or update a field map.
         */
        post: operations["create_field_map_api_v1_field_maps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/field-maps/{standard}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Default Field Map
         * @description Get the default field map for a standard (no source-specific overrides).
         */
        get: operations["get_default_field_map_api_v1_field_maps__standard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/field-maps/{standard}/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source Field Map
         * @description Get the source-specific field map override.
         */
        get: operations["get_source_field_map_api_v1_field_maps__standard___source__get"];
        put?: never;
        post?: never;
        /**
         * Delete Source Field Map
         * @description Delete a source-specific field map override.
         */
        delete: operations["delete_source_field_map_api_v1_field_maps__standard___source__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/field-maps/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Field Maps
         * @description Seed built-in default field maps. Non-destructive.
         */
        post: operations["seed_field_maps_api_v1_field_maps_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Rule
         * @description Create a new hunt rule via RuleCreationService.
         *
         *     The service sanitizes the SQL, applies CEL→SQL transpilation,
         *     validates column references, and optionally estimates query cost.
         */
        post: operations["create_rule_api_v1_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Rule Sql
         * @description Validate a SQL WHERE fragment without creating a rule.
         *
         *     Returns any syntax errors or validation issues found.
         */
        post: operations["validate_rule_sql_api_v1_rules_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Destinations
         * @description List alert destinations.
         */
        get: operations["list_destinations_api_v1_alerts_destinations_get"];
        put?: never;
        /**
         * Create Destination
         * @description Create an alert destination.
         */
        post: operations["create_destination_api_v1_alerts_destinations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/destinations/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Destination
         * @description Get an alert destination by name.
         */
        get: operations["get_destination_api_v1_alerts_destinations__name__get"];
        /**
         * Update Destination
         * @description Update an alert destination.
         */
        put: operations["update_destination_api_v1_alerts_destinations__name__put"];
        post?: never;
        /**
         * Delete Destination
         * @description Delete an alert destination.
         */
        delete: operations["delete_destination_api_v1_alerts_destinations__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Get engine version info.
         */
        get: operations["get_version_api_v1_system_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Get a redacted summary of current settings. No secrets exposed.
         */
        get: operations["get_settings_api_v1_system_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transforms/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Transform
         * @description Compile user source code to a WASM binary.
         *
         *     Proxies to the dfe-transform-compiler service. The response includes
         *     a base64-encoded WASM binary that can be passed directly to /test.
         */
        post: operations["compile_transform_api_v1_transforms_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transforms/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Transform
         * @description Run a compiled WASM transform against sample records.
         *
         *     Proxies to the dfe-transform-wasm service's /test endpoint.
         *     The wasm_base64 field should come directly from /compile.
         */
        post: operations["test_transform_api_v1_transforms_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertDestination */
        AlertDestination: {
            /**
             * Name
             * @description Unique destination identifier (used as filename)
             */
            name: string;
            /**
             * Url
             * @description Apprise notification URL (slack://, mailto://, etc.)
             */
            url: string;
            /**
             * Description
             * @description Human-readable description
             * @default
             */
            description: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** AlertDestinationSummary */
        AlertDestinationSummary: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Url Scheme
             * @description URL scheme (slack, mailto, etc.)
             * @default
             */
            url_scheme: string;
        };
        /**
         * BulkActionRequest
         * @description Bulk operation on multiple sources.
         */
        BulkActionRequest: {
            /**
             * Action
             * @description Action: enable, disable, delete
             */
            action: string;
            /**
             * Sources
             * @description Source names to act on
             */
            sources: string[];
        };
        /**
         * BulkActionResponse
         * @description Result of a bulk operation.
         */
        BulkActionResponse: {
            /** Action */
            action: string;
            /** Succeeded */
            succeeded?: string[];
            /** Failed */
            failed?: {
                [key: string]: string;
            }[];
        };
        /** CompileRequest */
        CompileRequest: {
            /**
             * Language
             * @enum {string}
             */
            language: "rust" | "go" | "assemblyscript";
            /**
             * Files
             * @description Source files. Key = filename, value = source content.
             */
            files: {
                [key: string]: string;
            };
        };
        /** CompileResponse */
        CompileResponse: {
            /** Wasm Base64 */
            wasm_base64: string;
            /** Wasm Bytes */
            wasm_bytes: number;
        };
        /** ConfigHistoryEntry */
        ConfigHistoryEntry: {
            /** Commit */
            commit: string;
            /** Message */
            message: string;
            /** Author */
            author: string;
            /** Date */
            date: string;
        };
        /** CostEstimate */
        CostEstimate: {
            /** Estimated Rows */
            estimated_rows?: number | null;
            /** Explain Plan */
            explain_plan?: string | null;
            /** Explain Duration Ms */
            explain_duration_ms?: number | null;
            /**
             * Window Minutes
             * @default 60
             */
            window_minutes: number;
            /** Warnings */
            warnings?: string[];
        };
        /** DeploymentHistoryEntry */
        DeploymentHistoryEntry: {
            /** Commit */
            commit: string;
            /** Message */
            message: string;
            /** Author */
            author: string;
            /** Date */
            date: string;
        };
        /** DeploymentSummary */
        DeploymentSummary: {
            /** Service */
            service: string;
            /** Instance */
            instance: string;
            /** Size */
            size?: string | null;
            /** Replicas */
            replicas?: number | null;
            /** Keda Enabled */
            keda_enabled?: boolean | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** EmittedRecord */
        EmittedRecord: {
            /** Key */
            key: string;
            /** Value */
            value: string;
            /** Headers */
            headers?: {
                [key: string]: string;
            };
        };
        /**
         * FetcherAuth
         * @description Fetcher authentication configuration.
         */
        FetcherAuth: {
            /**
             * Type
             * @description Auth type (oauth2, api_key, basic)
             */
            type: string;
            /**
             * Token Url
             * @description OAuth2 token URL
             */
            token_url?: string | null;
            /**
             * Client Id
             * @description OAuth2 client ID
             */
            client_id?: string | null;
            /**
             * Client Secret
             * @description OAuth2 client secret
             */
            client_secret?: string | null;
            /**
             * Api Key
             * @description API key
             */
            api_key?: string | null;
        };
        /**
         * FieldMap
         * @description A mapping from a detection/analytics standard's fields to DFE columns.
         *
         *     Two-tier resolution: a default map applies to all sources for a
         *     standard, and source-specific maps override individual entries.
         *
         *     Attributes:
         *         standard: Standard identifier (e.g. "sigma", "ecs", "cim").
         *         source: Source name this map applies to, or None for default map.
         *         version: Standard version (e.g. "8.11" for ECS). Informational.
         *         description: Human-readable description.
         *         inherits: Reference to base map (e.g. "_default"). Declarative
         *             — the resolver does not auto-fetch, caller is responsible.
         *         mappings: Dict of standard_field → dfe_column_name.
         */
        FieldMap: {
            /**
             * Standard
             * @description Standard identifier (sigma, ecs, cim)
             */
            standard: string;
            /**
             * Source
             * @description Source name, or None for the default map
             */
            source?: string | null;
            /**
             * Version
             * @description Standard version (e.g. '8.11' for ECS)
             */
            version?: string | null;
            /**
             * Description
             * @description Human description
             */
            description?: string | null;
            /**
             * Inherits
             * @description Reference to base map (declarative)
             */
            inherits?: string | null;
            /**
             * Mappings
             * @description standard_field → dfe_column_name
             */
            mappings?: {
                [key: string]: string;
            };
        };
        /** FieldMapSummary */
        FieldMapSummary: {
            /** Standard */
            standard: string;
            /** Source */
            source?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Version */
            version?: string | null;
            /**
             * Mapping Count
             * @default 0
             */
            mapping_count: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Username
             * @description Account name (admin, operator, viewer)
             */
            username: string;
            /**
             * Password
             * @description Plaintext password
             */
            password: string;
        };
        /** PaginatedResponse[AlertDestinationSummary] */
        PaginatedResponse_AlertDestinationSummary_: {
            /** Items */
            items: components["schemas"]["AlertDestinationSummary"][];
            /**
             * Total
             * @description Total matching items across all pages
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-based)
             */
            page: number;
            /**
             * Per Page
             * @description Items per page
             */
            per_page: number;
            /** Total Pages */
            readonly total_pages: number;
            /** Next Page */
            readonly next_page: number | null;
            /** Prev Page */
            readonly prev_page: number | null;
        };
        /** PaginatedResponse[DeploymentSummary] */
        PaginatedResponse_DeploymentSummary_: {
            /** Items */
            items: components["schemas"]["DeploymentSummary"][];
            /**
             * Total
             * @description Total matching items across all pages
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-based)
             */
            page: number;
            /**
             * Per Page
             * @description Items per page
             */
            per_page: number;
            /** Total Pages */
            readonly total_pages: number;
            /** Next Page */
            readonly next_page: number | null;
            /** Prev Page */
            readonly prev_page: number | null;
        };
        /** PaginatedResponse[FieldMapSummary] */
        PaginatedResponse_FieldMapSummary_: {
            /** Items */
            items: components["schemas"]["FieldMapSummary"][];
            /**
             * Total
             * @description Total matching items across all pages
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-based)
             */
            page: number;
            /**
             * Per Page
             * @description Items per page
             */
            per_page: number;
            /** Total Pages */
            readonly total_pages: number;
            /** Next Page */
            readonly next_page: number | null;
            /** Prev Page */
            readonly prev_page: number | null;
        };
        /** PaginatedResponse[ServiceConfigSummary] */
        PaginatedResponse_ServiceConfigSummary_: {
            /** Items */
            items: components["schemas"]["ServiceConfigSummary"][];
            /**
             * Total
             * @description Total matching items across all pages
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-based)
             */
            page: number;
            /**
             * Per Page
             * @description Items per page
             */
            per_page: number;
            /** Total Pages */
            readonly total_pages: number;
            /** Next Page */
            readonly next_page: number | null;
            /** Prev Page */
            readonly prev_page: number | null;
        };
        /** PaginatedResponse[SourceSummary] */
        PaginatedResponse_SourceSummary_: {
            /** Items */
            items: components["schemas"]["SourceSummary"][];
            /**
             * Total
             * @description Total matching items across all pages
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-based)
             */
            page: number;
            /**
             * Per Page
             * @description Items per page
             */
            per_page: number;
            /** Total Pages */
            readonly total_pages: number;
            /** Next Page */
            readonly next_page: number | null;
            /** Prev Page */
            readonly prev_page: number | null;
        };
        /** PermissionsResponse */
        PermissionsResponse: {
            /**
             * Roles
             * @description User's assigned roles
             */
            roles: string[];
            /**
             * Permissions
             * @description Resolved permissions from all roles
             */
            permissions: string[];
        };
        /**
         * RuleCreateRequest
         * @description Create a hunt rule via RuleCreationService.
         */
        RuleCreateRequest: {
            /**
             * Name
             * @description Human-readable rule name
             */
            name: string;
            /**
             * Severity
             * @description low|medium|high|critical
             * @default medium
             */
            severity: string;
            /**
             * Source Type
             * @description 'raw' (plain SQL) or 'hyperdx' (HyperDX saved search format)
             * @default raw
             */
            source_type: string;
            /**
             * User Sql
             * @description User-authored SQL WHERE fragment
             */
            user_sql: string;
            /**
             * Cel Filter
             * @description CEL expression filter
             */
            cel_filter?: string | null;
            /**
             * Hunt Name
             * @description Parent hunt name
             */
            hunt_name?: string | null;
            /**
             * Source
             * @description Source label (e.g. windows_audit)
             */
            source?: string | null;
            /**
             * Estimate Cost
             * @description Run EXPLAIN and estimate query cost
             * @default false
             */
            estimate_cost: boolean;
            /**
             * Cost Window Minutes
             * @description Window in minutes for cost estimate
             * @default 60
             */
            cost_window_minutes: number;
        };
        /** RuleCreateResponse */
        RuleCreateResponse: {
            rule: components["schemas"]["RuleResponse"];
            /** Sanitize Summary */
            sanitize_summary?: {
                [key: string]: unknown;
            };
            /** Sql Errors */
            sql_errors?: components["schemas"]["SqlValidationError"][];
            cost_estimate?: components["schemas"]["CostEstimate"] | null;
        };
        /** RuleResponse */
        RuleResponse: {
            /** Rule Id */
            rule_id: string;
            /** Name */
            name: string;
            /** Severity */
            severity: string;
            /** Source Db */
            source_db?: string | null;
            /** Source Table */
            source_table?: string | null;
            /** Where Clause */
            where_clause: string;
            /** Cel Filter */
            cel_filter?: string | null;
            /** Original Sql */
            original_sql: string;
            /** Hunt Name */
            hunt_name?: string | null;
            /** Source */
            source?: string | null;
            /** Warnings */
            warnings?: string[];
            /** Created At */
            created_at: string;
        };
        /** SampleRecord */
        SampleRecord: {
            /**
             * Key
             * @default
             */
            key: string;
            /** Value */
            value: string;
            /**
             * Timestamp
             * @default 0
             */
            timestamp: number;
            /** Headers */
            headers?: {
                [key: string]: string;
            };
        };
        /** ServiceConfigSummary */
        ServiceConfigSummary: {
            /** Service */
            service: string;
            /** Instance */
            instance: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * SettingsSummary
         * @description Redacted settings — no secrets.
         */
        SettingsSummary: {
            /** Clickhouse Host */
            clickhouse_host: string;
            /** Clickhouse Database */
            clickhouse_database: string;
            /** Sources Dir */
            sources_dir: string;
            /** Services Config Dir */
            services_config_dir: string;
            /** Hunt Dir */
            hunt_dir: string;
            /** Auth Enabled */
            auth_enabled: boolean;
            /** Auth Local Enabled */
            auth_local_enabled: boolean;
            /** Api Host */
            api_host: string;
            /** Api Port */
            api_port: number;
            /** Api Cors Origins */
            api_cors_origins: string[];
        };
        /** SizeResponse */
        SizeResponse: {
            /** Service */
            service: string;
            /** Instance */
            instance: string;
            /** Size */
            size: string;
            /**
             * Service Config Overrides
             * @description Service config overrides to apply (e.g. buffer sizes for this size)
             */
            service_config_overrides?: {
                [key: string]: unknown;
            };
        };
        /**
         * Source
         * @description The top-level data entity in the DFE platform.
         *
         *     A Source represents a distinct data stream entering the platform.
         *     Everything flows from the _source label.
         *
         *     See docs/SOURCE.md for the full specification.
         */
        Source: {
            /**
             * Source
             * @description The _source label — immutable identifier
             */
            source: string;
            /**
             * Display Name
             * @description Human-readable display name
             */
            display_name?: string | null;
            /**
             * Description
             * @description Source description
             */
            description?: string | null;
            /**
             * Enabled
             * @description Whether the source is active
             * @default true
             */
            enabled: boolean;
            /** @description Common schema header configuration */
            header?: components["schemas"]["SourceHeader"];
            /** @description Receiver match rule */
            match?: components["schemas"]["SourceMatch"] | null;
            /** @description Schema configuration */
            schema?: components["schemas"]["SourceSchema"];
            /** @description Transform stage (optional) */
            transform?: components["schemas"]["SourceTransform"] | null;
            /** @description SaaS API fetcher (optional) */
            fetcher?: components["schemas"]["SourceFetcher"] | null;
            /** @description Sigma field mappings (optional) */
            sigma?: components["schemas"]["SourceSigma"] | null;
            /**
             * Mapping Standards
             * @description Standards to generate mapping views for (e.g. sigma, ecs, cim)
             */
            mapping_standards?: string[];
        };
        /**
         * SourceFetcher
         * @description Fetcher configuration for SaaS API pull sources.
         */
        SourceFetcher: {
            /**
             * Source Type
             * @description Fetcher type (crowdstrike, m365, etc.)
             */
            source_type: string;
            /**
             * Base Url
             * @description API base URL
             */
            base_url?: string | null;
            /** @description Authentication config */
            auth?: components["schemas"]["FetcherAuth"] | null;
            /**
             * Poll Interval Secs
             * @description Polling interval in seconds
             * @default 300
             */
            poll_interval_secs: number;
        };
        /**
         * SourceHeader
         * @description Common schema header configuration.
         */
        SourceHeader: {
            /**
             * Type
             * @description Profile name (time_series, minimal, passthrough)
             * @default time_series
             */
            type: string;
            /**
             * Version
             * @description Common header version (semver)
             * @default 1.0.0
             */
            version: string;
        };
        /**
         * SourceMatch
         * @description Receiver match rule — how the receiver identifies this source.
         */
        SourceMatch: {
            /**
             * Field
             * @description JSON field to inspect
             */
            field: string;
            /**
             * Value
             * @description Expected value (exact match)
             */
            value: string;
        };
        /**
         * SourceResponse
         * @description Full source after create/update.
         */
        SourceResponse: {
            /** Source */
            source: string;
            /**
             * Message
             * @default ok
             */
            message: string;
        };
        /**
         * SourceSchema
         * @description Schema configuration for the source's ClickHouse table.
         */
        SourceSchema: {
            /**
             * Meta Schema
             * @description Base field definitions (YAML file reference)
             */
            meta_schema?: string | null;
            /**
             * Meta Schema Version
             * @description Meta schema version (semver)
             */
            meta_schema_version?: string | null;
            /**
             * Derived Schema
             * @description Source-specific field overrides (optional YAML reference)
             */
            derived_schema?: string | null;
            /**
             * Additional Fields
             * @description Extra fields/indexes (optional YAML reference)
             */
            additional_fields?: string | null;
            /**
             * Ttl Days
             * @description Data retention in days
             */
            ttl_days?: number | null;
            /**
             * Engine
             * @description Table engine (MergeTree, ReplicatedMergeTree, SharedMergeTree)
             * @default MergeTree
             */
            engine: string;
        };
        /**
         * SourceSigma
         * @description Sigma field mapping configuration for this source.
         */
        SourceSigma: {
            /**
             * Taxonomy
             * @description Built-in mapping set (e.g. 'windows')
             */
            taxonomy?: string | null;
            /**
             * Custom Mappings
             * @description Per-source field overrides (SigmaField: column_name)
             */
            custom_mappings?: {
                [key: string]: string;
            };
        };
        /**
         * SourceSummary
         * @description Lightweight source listing (for paginated list).
         */
        SourceSummary: {
            /**
             * Source
             * @description Source name / identifier
             */
            source: string;
            /** Display Name */
            display_name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Header Type */
            header_type?: string | null;
            /**
             * Has Transform
             * @default false
             */
            has_transform: boolean;
            /**
             * Has Fetcher
             * @default false
             */
            has_fetcher: boolean;
            /** Mapping Standards */
            mapping_standards?: string[];
        };
        /**
         * SourceTransform
         * @description Transform stage configuration (vector or wasm).
         */
        SourceTransform: {
            /**
             * Engine
             * @description Transform engine (vector or wasm)
             */
            engine: string;
            /**
             * Config File
             * @description Path to engine-specific config
             */
            config_file?: string | null;
            /**
             * Env
             * @description Per-transform ENV overrides
             */
            env?: {
                [key: string]: string;
            };
            /**
             * Files
             * @description Enrichment files (CSV, MMDB)
             */
            files?: string[];
        };
        /** SqlValidationError */
        SqlValidationError: {
            /** Message */
            message: string;
            /** Position */
            position?: number | null;
            /** Suggestion */
            suggestion?: string | null;
        };
        /** SqlValidationRequest */
        SqlValidationRequest: {
            /**
             * Sql
             * @description SQL WHERE fragment to validate
             */
            sql: string;
        };
        /** SqlValidationResponse */
        SqlValidationResponse: {
            /** Valid */
            valid: boolean;
            /** Errors */
            errors?: components["schemas"]["SqlValidationError"][];
        };
        /** TestRequest */
        TestRequest: {
            /**
             * Wasm Base64
             * @description Base64-encoded WASM binary from /compile
             */
            wasm_base64: string;
            /**
             * Records
             * @description Sample input records
             */
            records: components["schemas"]["SampleRecord"][];
            /**
             * Source Format
             * @default json
             * @enum {string}
             */
            source_format: "json" | "msgpack";
            /**
             * Sink Format
             * @default json
             * @enum {string}
             */
            sink_format: "json" | "msgpack";
        };
        /** TestResponse */
        TestResponse: {
            /** Emitted */
            emitted: components["schemas"]["EmittedRecord"][];
            /** Duration Ms */
            duration_ms: number;
            /** Wasm Memory Bytes */
            wasm_memory_bytes: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /**
             * Access Token
             * @description JWT Bearer token
             */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Token lifetime in seconds
             */
            expires_in: number;
            /**
             * User Id
             * @description Authenticated user ID
             */
            user_id: string;
            /**
             * Roles
             * @description User roles
             */
            roles: string[];
        };
        /** UserResponse */
        UserResponse: {
            /** Org Id */
            org_id: string;
            /** User Id */
            user_id: string;
            /** Roles */
            roles: string[];
            /** Permissions */
            permissions?: string[];
            /** Groups */
            groups?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /**
             * Version
             * @description Package version
             */
            version: string;
            /**
             * Python Version
             * @description Python interpreter version
             */
            python_version: string;
        };
        /** SeedResponse */
        dfe_engine__api__v1__deployments__SeedResponse: {
            /** Seeded */
            seeded: number;
        };
        /** ValidationResult */
        dfe_engine__api__v1__deployments__ValidationResult: {
            /** Valid */
            valid: boolean;
            /** Errors */
            errors?: string[];
            /** Warnings */
            warnings?: string[];
        };
        /** SeedResponse */
        dfe_engine__api__v1__fieldmaps__SeedResponse: {
            /** Seeded */
            seeded: number;
        };
        /** SeedResponse */
        dfe_engine__api__v1__services__SeedResponse: {
            /** Seeded */
            seeded: number;
        };
        /** ValidationResult */
        dfe_engine__api__v1__services__ValidationResult: {
            /** Valid */
            valid: boolean;
            /** Errors */
            errors?: string[];
        };
        /**
         * SeedResponse
         * @description Result of seeding built-in sources.
         */
        dfe_engine__api__v1__sources__SeedResponse: {
            /**
             * Seeded
             * @description Number of sources seeded
             */
            seeded: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_permissions_api_v1_auth_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionsResponse"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: {
                /** @description Search in source name and description */
                search?: string | null;
                /** @description Filter by enabled status */
                enabled?: boolean | null;
                /** @description Sort field (source, display_name, enabled) */
                sort_by?: string | null;
                /** @description Sort order: asc/desc */
                sort_order?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Items per page */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_SourceSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_sources__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_v1_sources__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_v1_sources__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_action_api_v1_sources_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_sources_api_v1_sources_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dfe_engine__api__v1__sources__SeedResponse"];
                };
            };
        };
    };
    list_service_configs_api_v1_services_get: {
        parameters: {
            query?: {
                /** @description Filter by service type */
                service?: string | null;
                /** @description Search in service/instance names */
                search?: string | null;
                /** @description Sort field (service, instance, updated_at) */
                sort_by?: string | null;
                /** @description Sort order: asc/desc */
                sort_order?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Items per page */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ServiceConfigSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_service_config_api_v1_services__service___instance__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_service_config_api_v1_services__service___instance__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_service_config_api_v1_services__service___instance__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_service_config_api_v1_services__service___instance__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dfe_engine__api__v1__services__ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_service_config_history_api_v1_services__service___instance__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_service_configs_api_v1_services_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dfe_engine__api__v1__services__SeedResponse"];
                };
            };
        };
    };
    list_deployments_api_v1_deployments_get: {
        parameters: {
            query?: {
                /** @description Filter by service type */
                service?: string | null;
                /** @description Search in service/instance names */
                search?: string | null;
                /** @description Sort field (service, instance, updated_at) */
                sort_by?: string | null;
                /** @description Sort order: asc/desc */
                sort_order?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Items per page */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DeploymentSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployment_api_v1_deployments__service___instance__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_deployment_api_v1_deployments__service___instance__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deployment_api_v1_deployments__service___instance__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_deployment_api_v1_deployments__service___instance__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dfe_engine__api__v1__deployments__ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deployment_history_api_v1_deployments__service___instance__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                service: string;
                instance: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_size_api_v1_deployments__service___instance__size__size__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service: string;
                instance: string;
                size: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_deployments_api_v1_deployments_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dfe_engine__api__v1__deployments__SeedResponse"];
                };
            };
        };
    };
    list_field_maps_api_v1_field_maps_get: {
        parameters: {
            query?: {
                /** @description Filter by mapping standard (e.g. sigma, ecs) */
                standard?: string | null;
                /** @description Search in standard/source names */
                search?: string | null;
                /** @description Sort field (standard, source, mapping_count) */
                sort_by?: string | null;
                /** @description Sort order: asc/desc */
                sort_order?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Items per page */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_FieldMapSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_field_map_api_v1_field_maps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldMap"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldMap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_default_field_map_api_v1_field_maps__standard__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                standard: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldMap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_field_map_api_v1_field_maps__standard___source__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                standard: string;
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldMap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_field_map_api_v1_field_maps__standard___source__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                standard: string;
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_field_maps_api_v1_field_maps_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dfe_engine__api__v1__fieldmaps__SeedResponse"];
                };
            };
        };
    };
    create_rule_api_v1_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_rule_sql_api_v1_rules_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SqlValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SqlValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_destinations_api_v1_alerts_destinations_get: {
        parameters: {
            query?: {
                /** @description Search in name/description */
                search?: string | null;
                /** @description Sort field (name, enabled) */
                sort_by?: string | null;
                /** @description Sort order: asc/desc */
                sort_order?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Items per page */
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_AlertDestinationSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_destination_api_v1_alerts_destinations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertDestination"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDestination"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_destination_api_v1_alerts_destinations__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDestination"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_destination_api_v1_alerts_destinations__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertDestination"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDestination"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_destination_api_v1_alerts_destinations__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_v1_system_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    get_settings_api_v1_system_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsSummary"];
                };
            };
        };
    };
    compile_transform_api_v1_transforms_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_transform_api_v1_transforms_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
